apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    isDefault: true
    editable: true
    jsonData:
      server: clickhouse
      port: 8123
      protocol: http
      username: default
      password: ""
      database: default
      # 连接池配置
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleTime: 30m
